apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "voice-cert-checker.fullname" . }}
  labels:
    {{- include "voice-cert-checker.labels" . | nindent 4 }}
data:
  config.yaml: |
     {{- with .Values.voicecertchecker }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
