version: '3.2'
services:

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/provisioning/:/etc/grafana/provisioning/:ro

  prometheus:
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  voice-cert-checker:
    image: rockosocko/voice-cert-checker:v0.0.1
    ports:
    - 8080:8080
    - 8081:8081
    volumes:
    - ./cert-checker/config.yaml:/app/config.yaml:ro
